/*
 * Copyright 2022. The ttrace authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package edu.tum.sse.dirts.analysis;

import com.github.javaparser.ast.body.*;
import edu.tum.sse.dirts.graph.DependencyGraph;

/**
 * Collects dependencies of NonType-nodes
 * <p>
 * Has to consider MethodDeclaration, ConstructorDeclaration, FieldDeclaration, EnumConstantDeclaration,
 * AnnotationMemberDeclaration, InitializerDeclaration
 */
public interface NonTypeDependencyCollector extends DependencyCollector<BodyDeclaration<?>> {

    /*
    Since generally all subclasses extend VoidVisitor, it is unfortunately not a compilation error
    if a subclass forgets to directly implement one of those methods

    Nevertheless, this can be used to check for completeness by clicking on the green circle on the left
    of each method generated by IntelliJ
     */

    void visit(MethodDeclaration n, DependencyGraph arg);

    void visit(ConstructorDeclaration n, DependencyGraph arg);

    void visit(FieldDeclaration n, DependencyGraph arg);

    void visit(EnumConstantDeclaration n, DependencyGraph arg);

    void visit(AnnotationMemberDeclaration n, DependencyGraph arg);

    void visit(InitializerDeclaration n, DependencyGraph arg);

}
